# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fc4dcec6bad96c82ad13dd254c960496eddc8ac1629e2d7375960ac60eba599f5fbbeca62603749dc0da0b764bd375daaac697211d7ac00d5d79364faaa27b

test:
  secret_key_base: 62868d25131248aae532071ea8acbf3ee7853ce02acf4dc4ab6f198b2ed5e0e932ee48321936bba020b27262ce514d91a8a4e637e0b032a320726703c00a6ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
